slam_toolbox:
  ros__parameters:

    use_sim_time: true

    # -------- 关键帧名，和你现在的 TF 对上 --------
    scan_topic: "/scan"          # 你亲自 echo 过的那个
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_footprint" # 你的 TF 里是 odom -> base_footprint -> base_link -> base_scan

    # -------- 工作模式：建图 --------
    mode: "mapping"

    # -------- 地图分辨率、更新频率 --------
    resolution: 0.05
    map_update_interval: 2.0
    publish_period_sec: 1.0

    # -------- 基础 SLAM 行为 --------
    use_scan_matching: true
    use_scan_barycenter: false

    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.1
    minimum_time_interval: 0.1
    maximum_laser_range: 8.0

    # -------- loop closure（先用温和默认） --------
    use_loop_closure: true
    loop_search_maximum_distance: 3.0
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.1
    loop_match_minimum_chain_size: 10
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # -------- 求解器配置（你原来那套，保留） --------
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "LEVENBERG_MARQUARDT"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"

    # -------- TF 缓冲 & 发布 --------
    transform_publish_period: 0.05
    tf_buffer_duration: 30.0
